server:
  port: 8080

spring:
  profiles:
    active: ${ACTIVE_PROFILE}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    generate-ddl: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs

jwt:
  secret: ${JWT_SECRET}
  access:
    duration: PT20M
  refresh:
    duration: P3D

crypto:
  algorithm: AES
  cipher: AES/CBC/PKCS5Padding
  key: ${CRYPTO_KEY}
  ivLength: 16
  encoding: UTF-8
  hash:
    name: HmacSHA256